# Generated by Django 4.0 on 2022-02-06 18:30

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='archived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='blogentry',
            name='state',
            field=django_fsm.FSMIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
